<a href="https://colab.research.google.com/github/Joaoplims/sna_roblox_kg/blob/main/Roblox_KG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.6.17)

## SETUP

In [2]:
from google.colab import userdata

API_KEY = userdata.get('roblox_oauth')
print( API_KEY )
HEADERS = {
    "x-api-key": API_KEY,
    "Content-Type": "application/json"
}

Bo3UKVecGk6QtPtNkA5tb2DIT+PFVGIxoNpqERPlnIdzQp2RZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluTnBaeTB5TURJeExUQTNMVEV6VkRFNE9qVXhPalE1V2lJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaGRXUWlPaUpTYjJKc2IzaEpiblJsY201aGJDSXNJbWx6Y3lJNklrTnNiM1ZrUVhWMGFHVnVkR2xqWVhScGIyNVRaWEoyYVdObElpd2lZbUZ6WlVGd2FVdGxlU0k2SWtKdk0xVkxWbVZqUjJzMlVYUlFkRTVyUVRWMFlqSkVTVlFyVUVaV1IwbDRiMDV3Y1VWU1VHeHVTV1I2VVhBeVVpSXNJbTkzYm1WeVNXUWlPaUl4TURJME5USXhPRGMwTnlJc0ltVjRjQ0k2TVRjNE1UUTVORGsxTml3aWFXRjBJam94TnpneE5Ea3hNelUyTENKdVltWWlPakUzT0RFME9URXpOVFo5LkRGV0VWVVh2N0dYdk5oWTVwbmFseW5wSjhHRUkwbzBoNEhsVDhobVdybFM2ZzZMWTF1M2gwSEZnRDZNY3VuUDN5XzhORS1GRWFHd3pEeDlYTVBEUWJiemRvMW90UEx1Z2t5WXNOVmZrRUpmV1JDNUwwcUp3VGN4dmdUYU1heldDcTMwRGFtWlBFNXVrTF85OHN6ZU9MWG5XOXBRMGV4cUtZelMzdFNTX0ZuNUIwcm5kb2NNeGltc3c5bTBONmhrQVBtdnBxckppb28zVDNCblkweUpCRWllT2YzSUdoM1JlTWcwYllvdE02b1pIek9GS096OElfZ1A3R0lKUnl4UDBaVWNxU0NxZGNzUHloem5UODkxYUpSRm40WTBZWHR4SEpsLVJNYnpRTDhST2RRZkxjcnlUVHIzdjZXVXgtZDZqVHFDU3ZzLXBHcERna1dONmJQVjc5Zw==

## Utilidades

In [3]:
def save_df_to_csv(df, filename="data_export.csv"):
    """
    Salva um DataFrame do pandas em um arquivo CSV.
    """
    try:
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"✅ Arquivo '{filename}' salvo com sucesso!")
    except Exception as e:
        print(f"❌ Erro ao salvar o arquivo: {e}")

# Exemplo de uso com os dados processados anteriormente:
# save_df_to_csv(df_users, "usuarios_roblox.csv")

## Função de Chamada para a API

In [4]:
import requests
import time
import random

def make_roblox_request(url, method="GET", params=None, data=None, max_retries=5, auto_paginate=False):
    """
    Função genérica para realizar chamadas à API do Roblox com suporte a Rate Limiting e Paginação.
    """
    all_data = []
    current_params = params.copy() if params else {}

    while True:
        retry_count = 0
        success = False

        while retry_count <= max_retries:
            try:
                response = requests.request(
                    method=method,
                    url=url,
                    headers=HEADERS,
                    params=current_params,
                    json=data
                )

                if response.status_code == 200:
                    res_json = response.json()

                    # Lógica de detecção: se houver uma chave 'data' e for uma lista, tratamos como paginável
                    if isinstance(res_json, dict) and 'data' in res_json and isinstance(res_json['data'], list):
                        page_items = res_json['data']
                        all_data.extend(page_items)

                        next_cursor = res_json.get('nextPageCursor')
                        if auto_paginate and next_cursor:
                            current_params['cursor'] = next_cursor
                            print(f"📄 Página processada. Buscando próxima página...")
                            success = True
                            break
                        else:
                            print(f"✅ Sucesso [{method}]: {url} (Total itens: {len(all_data)})")
                            return {"data": all_data}
                    else:
                        # Se não for uma lista paginável, retorna o JSON bruto (caso da Cloud API v2)
                        print(f"✅ Sucesso [{method}]: {url} (Objeto individual)")
                        return res_json

                elif response.status_code == 429:
                    retry_count += 1
                    wait_time = int(response.headers.get("retry-after", (2 ** retry_count) + random.uniform(0, 1)))
                    print(f"⚠️ Rate Limited (429). Aguardando {wait_time}s...")
                    time.sleep(wait_time)
                    continue
                else:
                    print(f"❌ Erro {response.status_code}: {response.text}")
                    return None
            except Exception as e:
                print(f"❌ Erro na requisição: {e}")
                return None

        if not success: break
    return None

## Teste chamadas

In [5]:
target_uid = 947838656
user_api_url = f"https://apis.roblox.com/cloud/v2/users/{target_uid}"

print(f"📡 Consultando dados para o usuário: {target_uid}...")
user_data_response = make_roblox_request(user_api_url)

import json
if user_data_response:
    print("✅ Resposta recebida:")
    print(json.dumps(user_data_response, indent=4))
else:
    print("❌ Não foi possível obter os dados do usuário.")

📡 Consultando dados para o usuário: 947838656...
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/947838656 (Objeto individual)
✅ Resposta recebida:
{
    "path": "users/947838656",
    "createTime": "2019-01-28T20:56:39.770Z",
    "id": "947838656",
    "name": "Scriptbloxian",
    "displayName": "Scriptbloxian",
    "about": "Lead Developer of Scriptbloxian Studios\nhttps://www.roblox.com/groups/4705120/Scriptbloxian-Studios",
    "locale": "en_us",
    "premium": true
}

In [6]:
import requests
import json

# Teste direto sem a função make_roblox_request
test_uid = 947838656
test_url = f"https://apis.roblox.com/cloud/v2/users/{test_uid}"

print(f"📡 Teste Direto (requests): {test_url}")
test_response = requests.get(test_url, headers=HEADERS)

print(f"Status Code: {test_response.status_code}")
try:
    raw_json = test_response.json()
    print("Raw JSON Response:")
    print(json.dumps(raw_json, indent=4))
except Exception as e:
    print(f"Erro ao decodificar JSON: {e}")
    print(f"Conteúdo bruto: {test_response.text}")

📡 Teste Direto (requests): https://apis.roblox.com/cloud/v2/users/947838656
Status Code: 200
Raw JSON Response:
{
    "path": "users/947838656",
    "createTime": "2019-01-28T20:56:39.770Z",
    "id": "947838656",
    "name": "Scriptbloxian",
    "displayName": "Scriptbloxian",
    "about": "Lead Developer of Scriptbloxian Studios\nhttps://www.roblox.com/groups/4705120/Scriptbloxian-Studios",
    "locale": "en_us",
    "premium": true
}

## Encontrar ID Seed Group

In [7]:
import time
# Cache do id do grupo mais popular (Scriptbloxian Studios) para evitar chamadas excessiva
ID_SEED_GROUP = 0
# Buscar o Grupo 'Scriptbloxian Studios'
# Pesquisas indicam que é um dos grupos mais populares (https://roblox.fandom.com/pt-br/wiki/Scriptbloxian_Studios)
# Grupo de desenvolvedor de jogos famoso
group_search_url = "https://groups.roblox.com/v1/groups/search/lookup?groupName=Scriptbloxian%20Studios"
group_search_results = make_roblox_request(group_search_url)

if group_search_results and group_search_results.get('data'):
    group_info = group_search_results['data'][0]
    group_id = group_info['id']
    ID_SEED_GROUP = group_id
    print(f"🎯 Grupo Encontrado: {group_info['name']} (ID: {group_id})")
else:
    print("❌ Grupo não encontrado ou erro na busca.")

✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/search/lookup?groupName=Scriptbloxian%20Studios (Total itens: 10)
🎯 Grupo Encontrado: Scriptbloxian Studios (ID: 4705120)

## Consulta de usuários

In [8]:
SAMPLE_SIZE = 25  # Parametrizável

# 2. Extrair membros do grupo semente
members_url = f"https://groups.roblox.com/v1/groups/{ID_SEED_GROUP}/users?sortOrder=Asc&limit={SAMPLE_SIZE}"
members_data = make_roblox_request(members_url, auto_paginate = False)

user_ids = []
if members_data and 'data' in members_data:
    user_ids = [member['user']['userId'] for member in members_data['data']]
    print(f"👥 Extraídos {len(user_ids)} usuários do grupo semente (ID: {ID_SEED_GROUP}).")
    print(f"Amostra de IDs: {user_ids}")
else:
    print("❌ Não foi possível extrair os membros do grupo.")

✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4705120/users?sortOrder=Asc&limit=25 (Total itens: 25)
👥 Extraídos 25 usuários do grupo semente (ID: 4705120).
Amostra de IDs: [947838656, 1027961385, 357829182, 244267273, 740396998, 731822913, 871184693, 262953699, 940534557, 970378427, 386824609, 747056849, 452079889, 519533783, 174791020, 363117394, 1041550312, 1038182669, 727787047, 557051148, 1023552809, 112492866, 363983769, 1014686408, 726703596]

### Processamento de Dados dos Usuários
Nesta etapa, consultamos a API de Usuários da Cloud API para obter detalhes como `createTime` e `locale`, calculando métricas derivadas.

In [9]:
from datetime import datetime, timezone
import pandas as pd
import time

processed_users = []
now = datetime.now(timezone.utc)

print(f"🔍 Processando {len(user_ids)} usuários...\n")

for uid in user_ids:
    url = f"https://apis.roblox.com/cloud/v2/users/{uid}"
    # A função corrigida agora retorna o objeto diretamente para a Cloud API v2
    user_data = make_roblox_request(url, auto_paginate=False)

    if user_data and user_data.get('createTime'):
        create_time_str = user_data['createTime']
        create_time_dt = datetime.fromisoformat(create_time_str.replace('Z', '+00:00'))

        delta = now - create_time_dt
        age = delta.days / 365.25

        processed_users.append({
            "user_id": user_data.get('id'),
            "display_name": user_data.get('displayName'),
            "created_at": create_time_str,
            "age_years": round(age, 2),
            "level": "Veterano" if age >= 10 else "Intermediário" if age >= 4 else "Iniciante"
        })
    else:
        print(f"⚠️ Falha ao obter detalhes do usuário {uid}")

    time.sleep(0.2)

df_users = pd.DataFrame(processed_users)
if not df_users.empty:
    display(df_users.head(10))
else:
    print("❌ Nenhum dado processado.")

🔍 Processando 25 usuários...

✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/947838656 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/1027961385 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/357829182 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/244267273 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/740396998 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/731822913 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/871184693 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/262953699 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/940534557 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/970378427 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/386824609 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/747056849 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/452079889 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/519533783 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/174791020 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/363117394 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/1041550312 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/1038182669 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/727787047 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/557051148 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/1023552809 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/112492866 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/363983769 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/1014686408 (Objeto individual)
✅ Sucesso [GET]: https://apis.roblox.com/cloud/v2/users/726703596 (Objeto individual)

,user_id,display_name,created_at,age_years,level
0,947838656,Scriptbloxian,2019-01-28T20:56:39.770Z,7.55,Intermediário
1,1027961385,Iamsmarterthanyahya3,2019-04-04T20:14:50.953Z,7.37,Intermediário
2,357829182,FallenGh,2017-08-02T17:39:17.880Z,9.04,Intermediário
3,244267273,kidsgivemesloppy,2017-02-20T05:17:52.727Z,9.49,Intermediário
4,740396998,Lloyd,2018-08-30T19:34:01.370Z,7.96,Intermediário
5,731822913,Kirill_pro300,2018-08-26T16:09:21.050Z,7.98,Intermediário
6,871184693,hunika201,2018-11-24T09:20:23.383Z,7.73,Intermediário
7,262953699,kevin2598,2017-03-14T15:33:27.687Z,9.43,Intermediário
8,940534557,furiouse_2,2019-01-23T01:56:45.160Z,7.56,Intermediário
9,970378427,Mid_Bacon,2019-02-16T16:54:47.510Z,7.50,Intermediário

### Exportação de Dados
Salvando o conjunto de dados processado em um arquivo CSV para uso externo.

In [ ]:
# Exportando os usuários processados
save_df_to_csv(df_users, "usuarios_roblox_processados.csv")

✅ Arquivo 'usuarios_roblox_processados.csv' salvo com sucesso!

## First Hop

### Mapeamento de Afiliações (First Hop)
Nesta etapa, buscamos todos os grupos de cada um dos usuários da nossa amostra inicial para descobrir as conexões entre eles.

In [10]:
graph_edges = []

print(f"🕸️ Iniciando mapeamento de afiliações para {len(user_ids)} usuários...")

for uid in user_ids:
    # Endpoint da API V1 para listar grupos/cargos do usuário
    affiliations_url = f"https://groups.roblox.com/v1/users/{uid}/groups/roles"

    # Como este endpoint retorna uma lista na chave 'data', nossa função make_roblox_request funcionará bem
    response = make_roblox_request(affiliations_url, auto_paginate=False)

    if response and 'data' in response:
        groups = response['data']
        for item in groups:
            group_info = item.get('group', {})
            role_info = item.get('role', {})

            # Registramos a aresta: Origem (User) -> Relação (Member) -> Destino (Group)
            edge = {
                "source_id": uid,
                "source_type": "User",
                "target_id": group_info.get('id'),
                "target_name": group_info.get('name'),
                "target_type": "Group",
                "role_name": role_info.get('name'),
                "role_rank": role_info.get('rank')
            }
            graph_edges.append(edge)

    # Pequeno delay para respeitar a API
    time.sleep(0.2)



# Criando um DataFrame para visualizar as conexões
df_graph = pd.DataFrame(graph_edges)
print(f"✅ Mapeamento concluído! Encontradas {len(df_graph)} conexões.")
display(df_graph.head(10))

🕸️ Iniciando mapeamento de afiliações para 25 usuários...
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/947838656/groups/roles (Total itens: 9)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1027961385/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/357829182/groups/roles (Total itens: 28)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/244267273/groups/roles (Total itens: 14)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/740396998/groups/roles (Total itens: 27)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/731822913/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/871184693/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/262953699/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/940534557/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/970378427/groups/roles (Total itens: 6)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/386824609/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/747056849/groups/roles (Total itens: 12)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/452079889/groups/roles (Total itens: 48)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/519533783/groups/roles (Total itens: 19)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/174791020/groups/roles (Total itens: 57)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/363117394/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1041550312/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1038182669/groups/roles (Total itens: 14)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/727787047/groups/roles (Total itens: 7)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/557051148/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1023552809/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/112492866/groups/roles (Total itens: 14)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/363983769/groups/roles (Total itens: 97)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1014686408/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/726703596/groups/roles (Total itens: 5)
✅ Mapeamento concluído! Encontradas 397 conexões.

,source_id,source_type,target_id,target_name,target_type,role_name,role_rank
0,947838656,User,257737430,Mischief Mechanics,Group,Owner,255
1,947838656,User,10975897,XP Games.,Group,[D] Developer,253
2,947838656,User,32794027,Titan Trainers,Group,Admin,254
3,947838656,User,32073904,Hero Rivals Arena,Group,Owner,255
4,947838656,User,16345189,Super Slide,Group,Owner,255
5,947838656,User,16176597,Shinoro Studios,Group,Owner,255
6,947838656,User,16170756,Magnetworks,Group,Owner,255
7,947838656,User,11979111,Scriptbloxian Creation Group,Group,Owner,255
8,947838656,User,4705120,Scriptbloxian Studios,Group,Lead Developer,255
9,1027961385,User,4705120,Scriptbloxian Studios,Group,Legend,1

In [11]:
# Exibindo uma amostra das arestas criadas
if graph_edges:
    print("Amostra das conexões:")
    for edge in graph_edges[:35]:
        print(f"Usuário [{edge['source_id']}] participando do Grupo [{edge['target_name']}] como '{edge['role_name']}' (Rank: {edge['role_rank']})")
else:
    print("❌ Nenhuma aresta encontrada")

Amostra das conexões:
Usuário [947838656] participando do Grupo [Mischief Mechanics] como 'Owner' (Rank: 255)
Usuário [947838656] participando do Grupo [XP Games.] como '[D] Developer' (Rank: 253)
Usuário [947838656] participando do Grupo [Titan Trainers] como 'Admin' (Rank: 254)
Usuário [947838656] participando do Grupo [Hero Rivals Arena] como 'Owner' (Rank: 255)
Usuário [947838656] participando do Grupo [Super Slide] como 'Owner' (Rank: 255)
Usuário [947838656] participando do Grupo [Shinoro Studios] como 'Owner' (Rank: 255)
Usuário [947838656] participando do Grupo [Magnetworks] como 'Owner' (Rank: 255)
Usuário [947838656] participando do Grupo [Scriptbloxian Creation Group] como 'Owner' (Rank: 255)
Usuário [947838656] participando do Grupo [Scriptbloxian Studios] como 'Lead Developer' (Rank: 255)
Usuário [1027961385] participando do Grupo [Scriptbloxian Studios] como 'Legend' (Rank: 1)
Usuário [357829182] participando do Grupo [Krabby Krew] como 'Anchovies' (Rank: 1)
Usuário [357829182] participando do Grupo [FFallenGh best epic noob gamer ever] como 'Owner' (Rank: 255)
Usuário [357829182] participando do Grupo [BIG Games™] como 'Fan' (Rank: 1)
Usuário [357829182] participando do Grupo [Triage Labs Development] como 'Supporter' (Rank: 1)
Usuário [357829182] participando do Grupo [Incentive] como 'Fan' (Rank: 1)
Usuário [357829182] participando do Grupo [Avatar Central Community] como 'Genesis Acolytes' (Rank: 2)
Usuário [357829182] participando do Grupo [HD Games.] como 'Fan' (Rank: 1)
Usuário [357829182] participando do Grupo [BloxCrafters ] como 'Fan' (Rank: 1)
Usuário [357829182] participando do Grupo [Beacon Studio] como 'Fans' (Rank: 1)
Usuário [357829182] participando do Grupo [Scriptbloxian Studios] como 'Legend' (Rank: 1)
Usuário [357829182] participando do Grupo [Schwifty Studios] como 'Fans' (Rank: 1)
Usuário [357829182] participando do Grupo [BIG Games Pets] como 'Fan' (Rank: 1)
Usuário [357829182] participando do Grupo [16bitplay Games] como 'Member' (Rank: 1)
Usuário [357829182] participando do Grupo [Overnight Games 1] como 'Member' (Rank: 1)
Usuário [357829182] participando do Grupo [Meme Team YT] como 'Members' (Rank: 1)
Usuário [357829182] participando do Grupo [Gone Gaming Studio] como 'Member' (Rank: 1)
Usuário [357829182] participando do Grupo [Electronic Publishers] como 'Follower' (Rank: 1)
Usuário [357829182] participando do Grupo [1Studio] como 'Members' (Rank: 1)
Usuário [357829182] participando do Grupo [Bee Swarm Simulator Club] como 'Member' (Rank: 1)
Usuário [357829182] participando do Grupo [Broken Wand Studios] como '✨ | Fans' (Rank: 1)
Usuário [357829182] participando do Grupo [Rumble Studios] como 'Fan' (Rank: 2)
Usuário [357829182] participando do Grupo [White Hat Studios.] como 'Fan' (Rank: 1)
Usuário [357829182] participando do Grupo [Lumber Tycoon 2 Fans] como 'Member' (Rank: 1)
Usuário [357829182] participando do Grupo [PenguinSquad] como 'Member' (Rank: 1)
Usuário [357829182] participando do Grupo [Tofuu Productions] como 'Beta Testers' (Rank: 2)

In [13]:
# Salvar o progresso do grafo
save_df_to_csv(df_graph, "conexoes_roblox_first_hop.csv")

✅ Arquivo 'conexoes_roblox_first_hop.csv' salvo com sucesso!

### Análise da Distribuição de Ranks
Nesta seção, visualizamos como os ranks (cargos) estão distribuídos nas conexões coletadas. Ranks mais altos (ex: 255) geralmente indicam donos ou administradores, enquanto ranks baixos (ex: 1) indicam membros comuns.

In [16]:
import pandas as pd

# Calculando a contagem absoluta
distribuicao = df_graph['role_rank'].value_counts().sort_index(ascending=False).reset_index()
distribuicao.columns = ['Role Rank', 'Quantidade']

# Calculando a porcentagem
distribuicao['Percentual (%)'] = (distribuicao['Quantidade'] / distribuicao['Quantidade'].sum() * 100).round(2)

# Exibindo a tabela completa
display(distribuicao)

    Role Rank  Quantidade  Percentual (%)
0         255           9            2.27
1         254           1            0.25
2         253           1            0.25
3         245           1            0.25
4         244           1            0.25
5         154           1            0.25
6         150           3            0.76
7          30           1            0.25
8          10           4            1.01
9           7           1            0.25
10          5           5            1.26
11          3           2            0.50
12          2          27            6.80
13          1         340           85.64

## Second Hop

In [17]:
# Extraindo os IDs de grupos únicos (target_id) do DataFrame de conexões
unique_group_ids = df_graph['target_id'].unique().tolist()

print(f"🔍 Total de conexões: {len(df_graph)}")
print(f"🎯 Total de grupos únicos identificados: {len(unique_group_ids)}")
print(f"Amostra dos IDs: {unique_group_ids[:10]}")

🔍 Total de conexões: 397
🎯 Total de grupos únicos identificados: 299
Amostra dos IDs: [257737430, 10975897, 32794027, 32073904, 16345189, 16176597, 16170756, 11979111, 4705120, 34990762]

### Coleta de Membros por Grupo (Second Hop)
Nesta etapa, para cada grupo mapeado anteriormente, solicitamos a lista de membros (limitada aos 20 primeiros) para construir a rede de conexões de segundo nível.

In [19]:
second_hop_edges = []


print(f"🚀 Iniciando coleta de membros para {len(unique_group_ids)} grupos...")

for i, group_id in enumerate(unique_group_ids):
    # Progresso a cada 20 grupos para não poluir o console
    if i % 20 == 0:
        print(f"📦 Processando grupo {i}/{len(unique_group_ids)}...")

    # Endpoint para listar membros do grupo
    members_url = f"https://groups.roblox.com/v1/groups/{group_id}/users?sortOrder=Asc&limit={SAMPLE_SIZE}"

    response = make_roblox_request(members_url, auto_paginate=False)

    if response and 'data' in response:
        for member in response['data']:
            user_info = member.get('user', {})
            role_info = member.get('role', {})

            second_hop_edges.append({
                "source_id": user_info.get('userId'),
                "source_name": user_info.get('username'),
                "source_type": "User",
                "target_id": group_id,
                "target_type": "Group",
                "role_name": role_info.get('name'),
                "role_rank": role_info.get('rank')
            })

    # Delay para evitar 429 (Rate Limit)
    time.sleep(0.1)

df_second_hop = pd.DataFrame(second_hop_edges)
print(f"\n✅ Coleta concluída!")
print(f"Total de novas conexões encontradas: {len(df_second_hop)}")
display(df_second_hop.head(10))

🚀 Iniciando coleta de membros para 299 grupos...
📦 Processando grupo 0/299...
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/10975897/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/32794027/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/32073904/users?sortOrder=Asc&limit=25 (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/16345189/users?sortOrder=Asc&limit=25 (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/16176597/users?sortOrder=Asc&limit=25 (Total itens: 6)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/16170756/users?sortOrder=Asc&limit=25 (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/11979111/users?sortOrder=Asc&limit=25 (Total itens: 10)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4705120/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/34990762/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/15749446/users?sortOrder=Asc&limit=25 (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2703304/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5186373/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4350296/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5112875/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5028964/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4673266/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2589590/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3642592/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3959677/users?sortOrder=Asc&limit=25 (Total itens: 25)
📦 Processando grupo 20/299...
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3233280/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4557831/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2900384/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3794780/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2719502/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4562839/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3982592/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4430841/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3333298/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2851520/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2658221/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3377227/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4550671/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2782840/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3329643/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3823645/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3049798/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/10446127/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/12149305/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/13632331/users?sortOrder=Asc&limit=25 (Total itens: 25)
📦 Processando grupo 40/299...
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5510485/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4939446/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2726951/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/787581/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3461453/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3261090/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3352473/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/12236132/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5363999/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35927358/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35974201/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35660980/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/33097934/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/12836673/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4843020/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/15924139/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/1235888/users?sortOrder=Asc&limit=25 (Total itens: 25)
📦 Processando grupo 60/299...
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3002493/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4740025/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5522949/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/12420072/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/997074/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/6887275/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/9793279/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/9050583/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4031614/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4660370/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4589677/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2722126/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4855311/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4780847/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2618316/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3146429/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/10/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3338997/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4788489/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/7/users?sortOrder=Asc&limit=25 (Total itens: 25)
📦 Processando grupo 80/299...
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2795651/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/13189664/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4372130/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/14461694/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/555253/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/7947655/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/12428456/users?sortOrder=Asc&limit=25 (Total itens: 6)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4546767/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/14469199/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/15794692/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/15491373/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3239513/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5847588/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35229570/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/36028697/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/8509669/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/33298472/users?sortOrder=Asc&limit=25 (Total itens: 25)
📦 Processando grupo 100/299...
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/34671275/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4035125/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/16409914/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5664878/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5773173/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/13751258/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/7165738/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/15156286/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/13999121/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/11346367/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/9217776/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/13974419/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/7722880/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/14279387/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3991320/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/6521321/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/14715718/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/14600303/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/13758476/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/12463875/users?sortOrder=Asc&limit=25 (Total itens: 25)
📦 Processando grupo 120/299...
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/2841240/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/8327387/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4886976/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/6897155/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4488708/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/6039961/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/11453249/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3974428/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/10751993/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/10287445/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/7674505/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/7823755/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/7662206/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/9499273/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/5498200/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/10030212/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/4097667/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/3367671/users?sortOrder=Asc&limit=25 (Total itens: 25)
📦 Processando grupo 140/299...
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35906875/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/34258454/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35657938/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/32786900/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/848370702/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35016574/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/1064893764/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/15090884/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/34321086/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/34873522/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35302104/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35812225/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/34106550/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/32539357/users?sortOrder=Asc&limit=25 (Total itens: 25)
📦 Processando grupo 160/299...
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35154829/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/34644452/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35061735/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/35177826/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/16397129/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/34051074/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/1226491/users?sortOrder=Asc&limit=25 (Total itens: 25)
❌ Erro 400: {"errors":[{"code":3,"message":"The user is invalid or does not exist.","userFacingMessage":"The user is invalid or does not exist."}]}
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/33659247/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/34913035/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/34440699/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/33820338/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/9546376/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/15150189/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/13104578/users?sortOrder=Asc&limit=25 (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/groups/17219742/users?sortOrder=Asc&limit=25 (Total itens: 25)

,source_id,source_name,source_type,target_id,target_type,role_name,role_rank
0,1711299025,PrincessRayn44,User,10975897,Group,[G] Gamer,1
1,2558399989,Izzybotyourgot,User,10975897,Group,[G] Gamer,1
2,2591680131,batmankian900,User,10975897,Group,[G] Gamer,1
3,2489593516,lonzell_9,User,10975897,Group,[G] Gamer,1
4,2335800629,WDGanns,User,10975897,Group,[G] Gamer,1
5,2560085628,joew5709,User,10975897,Group,[G] Gamer,1
6,2634340174,RICHIE1448,User,10975897,Group,[G] Gamer,1
7,14358363,xEmberz,User,10975897,Group,[G] Gamer,1
8,2339442932,Toenailskidnoob,User,10975897,Group,[G] Gamer,1
9,1469500187,dkdkjekdndn,User,10975897,Group,[G] Gamer,1

In [20]:
# Salvando o resultado do segundo salto
save_df_to_csv(df_second_hop, "conexoes_roblox_second_hop.csv")

✅ Arquivo 'conexoes_roblox_second_hop.csv' salvo com sucesso!

In [22]:
from google.colab import drive
import os

# 1. Montar o Drive para salvamento persistente
drive.mount('/content/drive')
save_path = '/content/drive/My Drive/roblox_graph_data/'
os.makedirs(save_path, exist_ok=True)

# 2. Remover duplicatas do Second Hop
df_second_hop = df_second_hop.drop_duplicates(subset=['source_id', 'target_id'])
print(f"✅ Duplicatas removidas. Total de conexões únicas: {len(df_second_hop)}")

# 3. Extrair usuários únicos do second hop para mapear suas outras afiliações
new_user_ids = df_second_hop['source_id'].unique().tolist()
second_hop_affiliations = []

print(f"🕸️ Mapeando afiliações para {len(new_user_ids)} novos usuários...")

for i, uid in enumerate(new_user_ids):
    affiliations_url = f"https://groups.roblox.com/v1/users/{uid}/groups/roles"
    response = make_roblox_request(affiliations_url, auto_paginate=False)

    if response and 'data' in response:
        for item in response['data']:
            group_info = item.get('group', {})
            role_info = item.get('role', {})
            second_hop_affiliations.append({
                "source_id": uid,
                "source_type": "User",
                "target_id": group_info.get('id'),
                "target_name": group_info.get('name'),
                "target_type": "Group",
                "role_name": role_info.get('name'),
                "role_rank": role_info.get('rank')
            })

    # 4. Salvar no Drive a cada 200 usuários
    if (i + 1) % 200 == 0:
        temp_df = pd.DataFrame(second_hop_affiliations)
        temp_df.to_csv(f"{save_path}checkpoint_batch_{i+1}.csv", index=False)
        print(f"💾 Checkpoint salvo: {i+1} usuários processados.")

    time.sleep(0.2)

# Resultado final do mapeamento expandido
df_expanded_graph = pd.DataFrame(second_hop_affiliations)
df_expanded_graph.to_csv(f"{save_path}full_second_hop_affiliations.csv", index=False)
print(f"✅ Mapeamento completo concluído! Total de arestas: {len(df_expanded_graph)}")
display(df_expanded_graph.head())

A saída de streaming foi truncada nas últimas 5000 linhas.
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/18034215/groups/roles (Total itens: 6)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/18596359/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/15986689/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/104415244/groups/roles (Total itens: 95)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/163626872/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/173448199/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/173625430/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/167418632/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/170431153/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/169903686/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/83225614/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/95757067/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/187802673/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/192681756/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/186560749/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/190093412/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/193243948/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/193287499/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/189942601/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/109961725/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/88171074/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/191272422/groups/roles (Total itens: 6)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/188835172/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/180359825/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/168807007/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/166882237/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/195027307/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/195198993/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3095250/groups/roles (Total itens: 98)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/862825092/groups/roles (Total itens: 22)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2956068077/groups/roles (Total itens: 10)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2656561541/groups/roles (Total itens: 14)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2606946475/groups/roles (Total itens: 34)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2552265541/groups/roles (Total itens: 17)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2364194630/groups/roles (Total itens: 70)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1473832003/groups/roles (Total itens: 74)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2757983265/groups/roles (Total itens: 79)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2540918385/groups/roles (Total itens: 8)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1263806195/groups/roles (Total itens: 45)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/287650388/groups/roles (Total itens: 50)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3040949947/groups/roles (Total itens: 18)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1229815764/groups/roles (Total itens: 97)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3093860504/groups/roles (Total itens: 20)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1186587364/groups/roles (Total itens: 78)
💾 Checkpoint salvo: 1800 usuários processados.
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2317829943/groups/roles (Total itens: 36)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3061191741/groups/roles (Total itens: 21)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1395999415/groups/roles (Total itens: 55)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2372523582/groups/roles (Total itens: 104)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1472674129/groups/roles (Total itens: 36)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2380707231/groups/roles (Total itens: 51)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1398207254/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/859946670/groups/roles (Total itens: 96)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2826479293/groups/roles (Total itens: 120)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/912348/groups/roles (Total itens: 68)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/715267227/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/742782842/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/588232203/groups/roles (Total itens: 99)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/711358033/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/633903912/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/743248284/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/676522014/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/458515349/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/382692122/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/488629645/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/452501088/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/621876460/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/594460517/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/701194146/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/684495237/groups/roles (Total itens: 65)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/512089050/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/718264294/groups/roles (Total itens: 9)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/293606084/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/590571983/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/632341657/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/742603720/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/721189875/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/741661633/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/734272737/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2401118228/groups/roles (Total itens: 41)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1155012850/groups/roles (Total itens: 49)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/868952250/groups/roles (Total itens: 26)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/479032666/groups/roles (Total itens: 15)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2579323892/groups/roles (Total itens: 72)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1571736424/groups/roles (Total itens: 40)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3571614399/groups/roles (Total itens: 50)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3768410264/groups/roles (Total itens: 10)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2355822821/groups/roles (Total itens: 97)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2490505283/groups/roles (Total itens: 45)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3399736563/groups/roles (Total itens: 122)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1981783224/groups/roles (Total itens: 76)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2497525148/groups/roles (Total itens: 41)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1782221286/groups/roles (Total itens: 42)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3667023103/groups/roles (Total itens: 63)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2408679231/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2210226540/groups/roles (Total itens: 98)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2026789929/groups/roles (Total itens: 79)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3646996907/groups/roles (Total itens: 40)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3633822832/groups/roles (Total itens: 8)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1472833041/groups/roles (Total itens: 31)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/414281205/groups/roles (Total itens: 149)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1775964193/groups/roles (Total itens: 23)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2261730838/groups/roles (Total itens: 101)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2823905998/groups/roles (Total itens: 6)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/138659091/groups/roles (Total itens: 93)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1123885699/groups/roles (Total itens: 17)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1743272519/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1711474126/groups/roles (Total itens: 11)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1039953687/groups/roles (Total itens: 95)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1862763184/groups/roles (Total itens: 89)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/558698156/groups/roles (Total itens: 13)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1507826940/groups/roles (Total itens: 97)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1925966273/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1924319203/groups/roles (Total itens: 61)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1825633296/groups/roles (Total itens: 93)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1858685830/groups/roles (Total itens: 101)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1634260416/groups/roles (Total itens: 73)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1474213128/groups/roles (Total itens: 53)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1562740163/groups/roles (Total itens: 116)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1709998435/groups/roles (Total itens: 96)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1012388814/groups/roles (Total itens: 94)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2016867678/groups/roles (Total itens: 19)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1513805463/groups/roles (Total itens: 92)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1374822098/groups/roles (Total itens: 95)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1956276613/groups/roles (Total itens: 80)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1919450246/groups/roles (Total itens: 86)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2289651265/groups/roles (Total itens: 69)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1871732040/groups/roles (Total itens: 85)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1674378579/groups/roles (Total itens: 135)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/40397833/groups/roles (Total itens: 102)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1105836588/groups/roles (Total itens: 37)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/293215507/groups/roles (Total itens: 97)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/332519884/groups/roles (Total itens: 54)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1583332708/groups/roles (Total itens: 105)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2032016265/groups/roles (Total itens: 113)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1497173850/groups/roles (Total itens: 81)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1411711236/groups/roles (Total itens: 99)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2381159673/groups/roles (Total itens: 20)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2420677024/groups/roles (Total itens: 101)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1949415844/groups/roles (Total itens: 79)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1814614716/groups/roles (Total itens: 102)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1991960233/groups/roles (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1229944239/groups/roles (Total itens: 88)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1482132171/groups/roles (Total itens: 95)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2023544860/groups/roles (Total itens: 36)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2459592587/groups/roles (Total itens: 47)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/10199288/groups/roles (Total itens: 87)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2857143613/groups/roles (Total itens: 94)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2659443953/groups/roles (Total itens: 59)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3075756656/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2794816095/groups/roles (Total itens: 112)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1080964792/groups/roles (Total itens: 49)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1642633956/groups/roles (Total itens: 40)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2956749819/groups/roles (Total itens: 21)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1948201/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/5720482/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/10753134/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2211788/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/6197945/groups/roles (Total itens: 20)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/11045949/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/9390183/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/12652214/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2968557/groups/roles (Total itens: 68)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/13805173/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/19529337/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/16513307/groups/roles (Total itens: 22)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/19832711/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/19834493/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/19876592/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/18463530/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/19952588/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/19959273/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/19505757/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/18079257/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/19013105/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/20036798/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/14959697/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/20088182/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/19703838/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/393013107/groups/roles (Total itens: 9)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/755492001/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/2819164688/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/3310169188/groups/roles (Total itens: 6)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1080270179/groups/roles (Total itens: 47)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/725701072/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/938464833/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/663237460/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/481845464/groups/roles (Total itens: 103)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/919675423/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/911155108/groups/roles (Total itens: 27)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/935202010/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/939194285/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/195156040/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/175484867/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/473113195/groups/roles (Total itens: 25)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/500145831/groups/roles (Total itens: 4)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/926099864/groups/roles (Total itens: 10)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/915286348/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/903669120/groups/roles (Total itens: 6)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/714846710/groups/roles (Total itens: 125)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/852453614/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/881301149/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/909227356/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/938289447/groups/roles (Total itens: 3)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/925757860/groups/roles (Total itens: 41)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/938282115/groups/roles (Total itens: 23)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/938801204/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/150802202/groups/roles (Total itens: 27)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/896588853/groups/roles (Total itens: 5)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1108032657/groups/roles (Total itens: 41)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/19256410/groups/roles (Total itens: 35)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1442116192/groups/roles (Total itens: 2)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/1894926845/groups/roles (Total itens: 1)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/398555995/groups/roles (Total itens: 100)
✅ Sucesso [GET]: https://groups.roblox.com/v1/users/178289277/groups/roles (Total itens: 7)

,source_id,source_type,target_id,target_name,target_type,role_name,role_rank
0,1711299025,User,13420266,PLANETERIUM,Group,⭐ Player,1
1,1711299025,User,35669818,크롱 스튜디오,Group,멤버,1
2,1711299025,User,393625465,Anime Slap Tower,Group,Member,1
3,1711299025,User,33092455,HAKI SHOP,Group,🦋Member,2
4,1711299025,User,16805444,Denis dave,Group,Member,1

## Montagem Knowladge Graph

In [26]:
import networkx as nx
import matplotlib.pyplot as plt

# 1. Instanciar o grafo direcionado
G = nx.DiGraph()

print(f"🏗️ Construindo grafo a partir de {len(df_expanded_graph)} conexões...")

# 2. Adicionar arestas e atributos usando itertuples (MUITO mais rápido)
for row in df_expanded_graph.itertuples(index=False):
    # Acessamos os valores usando notação de ponto em vez de colchetes
    user_node = f"U_{row.source_id}"
    group_node = f"G_{row.target_id}"

    # Adiciona nós com metadados de tipo
    G.add_node(user_node, type='User', label=row.source_id)
    G.add_node(group_node, type='Group', name=row.target_name, label=row.target_id)

    # Cria a aresta com atributos de Rank
    G.add_edge(
        user_node,
        group_node,
        role=row.role_name,
        rank=row.role_rank
    )

# 3. Métricas básicas do Grafo
num_nodes = G.number_of_nodes()
num_edges = G.number_of_edges()

print(f"✅ Grafo de Conhecimento montado!")
print(f"🔹 Total de Nós: {num_nodes}")
print(f"🔸 Total de Arestas: {num_edges}")

# Exibir os 5 grupos com maior Grau de Entrada (In-Degree)
# O in_degree revela exatamente quantos usuários da sua amostra estão naquele grupo
in_degree_dict = dict(G.in_degree())
sorted_in_degree = sorted(in_degree_dict.items(), key=lambda item: item[1], reverse=True)

print("\n🔝 Top 5 Grupos Hubs da Rede (Mais populares entre a amostra):")
for node, degree in sorted_in_degree[:5]:
    # Como filtramos por in_degree, os top serão inevitavelmente nós de 'Group' (G_)
    node_data = G.nodes[node]
    name = node_data.get('name', 'Unknown')
    print(f"- {node} ({name}): {degree} membros mapeados")

🏗️ Construindo grafo a partir de 266724 conexões...
✅ Grafo de Conhecimento montado!
🔹 Total de Nós: 72862
🔸 Total de Arestas: 266724

🔝 Top 5 Grupos Hubs da Rede (Mais populares entre a amostra):
- G_4705120 (Scriptbloxian Studios): 1265 membros mapeados
- G_3333298 (Rumble Studios): 1217 membros mapeados
- G_3982592 (Bee Swarm Simulator Club): 1190 membros mapeados
- G_3959677 (BIG Games Pets): 1132 membros mapeados
- G_3461453 (Nosniy Games): 1100 membros mapeados

### Análise de Influência (Centralidade)
Nesta etapa, calculamos o `degree_centrality` para identificar quais usuários possuem o maior número de conexões com diferentes grupos, indicando perfis altamente ativos ou influentes na rede mapeada.

In [27]:
# Calculando a centralidade de grau para os nós
centrality = nx.degree_centrality(G)

# Filtrando apenas nós do tipo 'User'
user_centrality = {
    node: score for node, score in centrality.items()
    if G.nodes[node].get('type') == 'User'
}

# Ordenando para encontrar os Top 10 usuários
sorted_users = sorted(user_centrality.items(), key=lambda x: x[1], reverse=True)[:10]

print("🏆 Top 10 Usuários mais conectados no Grafo:")
for node, score in sorted_users:
    user_id = G.nodes[node].get('label')
    # Tentando buscar o nome no dataframe original se disponível
    user_name = df_second_hop[df_second_hop['source_id'] == user_id]['source_name'].iloc[0] if user_id in df_second_hop['source_id'].values else "Unknown"
    print(f"- Usuário {user_id} ({user_name}): Score {score:.6f}")

🏆 Top 10 Usuários mais conectados no Grafo:
- Usuário 5420068 (HiddoDev): Score 0.002059
- Usuário 5080868749 (dbs_johnny): Score 0.002059
- Usuário 4166356547 (k2_nz): Score 0.002059
- Usuário 2308665054 (CodeMerge): Score 0.002059
- Usuário 3774652516 (Savitar1196): Score 0.002059
- Usuário 2607226698 (rice_fi78): Score 0.002059
- Usuário 3065793394 (jett273322): Score 0.002059
- Usuário 414281205 (Captainboy124): Score 0.002045
- Usuário 2235085140 (HudsonS1216): Score 0.002045
- Usuário 7126325238 (ikher501): Score 0.002045